---
#
# roles/user/tasks/main.yml
#

- name: create groups
  group:
    name: "{{ item.group }}"
    gid: "{{ item.gid }}"
  with_items:
  - { group: 'ncupuser', gid: '4519' }
  - { group: 'ncadmin',  gid: '4520' }

# - name: create user
#   user:
#     state: present
#     name: {{ user."{{ item }}"_name }}
#     group: {{ user."{{ item }}"_group }}
#     password: {{ user."{{ item }}"_password }}
#     shell: /bin/bash
#   with_items:
#   - ncupuser
#   - ncadmin

- name: make users
  user:
    state: present
    name: "{{ item.name }}"
    group: "{{ item.group }}"
    uid: "{{ item.uid }}"
    password: "{{ item.password }}"
    shell: /bin/bash
  with_items:
  - { name: 'ncupuser', group: 'ncupuser', uid: '4519', password: 'bDbkZGUW2HMjwVzev9hyxsDw' }
  - { name: 'ncadmin' , group: 'ncadmin' , uid: '4520', password: '9uSqzPzih5CUxqyFb6xvEP52' }

- name: setting NOPASSWORD
  lineinfile:
    dest: /etc/sudoers
    backup: yes
    line: "{{ item }}"
  with_items:
  - 'ncadmin  ALL=(ALL) NOPASSWD: ALL'
  - 'ncupuser ALL=(ALL) NOPASSWD: /bin/systemctl'
  ignore_errors: true

- name: mkdir '.ssh'
  file:
    state: directory
    path: /home/{{ item.name }}/.ssh
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0700
  with_items:
  - { name: 'ncupuser', group: 'ncupuser' }
  - { name: 'ncadmin' , group: 'ncadmin'  }

- name: copy public key
  copy:
    src: roles/user/files/id_rsa-{{ item.name }}.pub
    dest: /home/{{ item.name }}/.ssh/authorized_keys
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items:
  - { name: 'ncupuser', group: 'ncupuser' }
  - { name: 'ncadmin' , group: 'ncadmin'  }

# - name: copy public key
#   copy:
#     src: roles/user/files/id_rsa-upuser.pub
#     dest: /home/upuser/.ssh/authorized_keys
#     owner: upuser
#     group: upuser
#     mode: 0644

- name: copy secret key ( upuser )
  copy:
    src: roles/user/files/id_rsa-{{ item.name }}
    dest: /home/{{ item.name }}/.ssh/id_rsa-{{ item.name }}
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0600
  with_items:
  - { name: 'ncupuser', group: 'ncupuser' }

- name: ssh config
  copy:
    src: roles/user/files/config-{{ item.name }}
    dest: /home/{{ item.name }}/.ssh/config
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    mode: 0644
  with_items:
  - { name: 'ncupuser', group: 'ncupuser' }
  - { name: 'ncadmin',  group: 'ncadmin'  }

# - name: copy and setting public key from vagrant
#   shell: cp /home/vagrant/.ssh/authorized_keys              \
#             /home/{{ user.user_name }}/.ssh/authorized_keys \
#          &&                                                 \
#          chown {{ user.user_name }}.{{ user.user_group }}    \ 
#          /home/{{ user.user_name }}/.ssh/authorized_keys
#   when: node == "vagrant"  


- name: setting prompt color
  shell: echo '{{ item.export }}' >> {{ item.path }}/.bashrc
  with_items:
  - { export: 'export PS1="\[\033[0;31m\][\t][\u@\h \W]\\$\[\033[0m\] "',  path: '/root'         }
  - { export: 'export PS1="\[\033[0;33m\][\t][\u@\h \W]\\$\[\033[0m\] "',  path: '/home/ncupuser'  }
  - { export: 'export PS1="\[\033[1;31m\][\t][\u@\h \W]\\$\[\033[0m\] "',  path: '/home/ncadmin' }
